import { getServerSession } from 'next-auth';
import './globals.css'
import type { Metadata } from 'next';
import { authOptions } from '@/lib/auth';
import Provider from './providers/sessionProvider';
import ProtectedRoute from './protected';
import LoginModal from './components/modals/LoginModal';
import RegisterModal from './components/modals/RegisterModal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <LoginModal />
        <RegisterModal />
        <Provider session={session}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
